### ISSUE TITLE
Feature Request on Search Results Page

### ISSUE THREAD

**Issue by waymondrang** [chiyeon/pretty-web-reg#2]
On the "Schedule of Classes search results" page, there is an error message that appears when submitting a blank form which reads

> You must specify an Instructor, Course Code range, Department, or Breadth category

This message should be a different color than the rest of the text to emphasize its importance.

I noticed that you included a CSS declaration that overrides all of the text colors on the page.

```css
* {
    color: rgb(242, 242, 242) !important;
    font-family: Poppins, sans-serif !important;
}
```

Perhaps this declaration may be too explicit, as it also overrides the colors of links and titles. I would suggest using a different method to achieve white color while preserving the important colored indicators of error messages and links.

Happy holidays and Merry Christmas!
